<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository{

    public function findByCategory($category)
       { $query = $this->createQueryBuilder('c')
            ->innerJoin("c.providers", "p")
            ->select("c","p as provider")
            ->where('c.id = :id')
            ->setParameter("id", $category);

        return $query->getQuery()->getResult();
    }
}