<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function newComments($max_results)
    {
        $query = $this->createQueryBuilder('c')
            ->leftJoin("c.provider", "p")
            ->leftJoin("c.member", "m")
            ->orderBy("c.date", "DESC")
            ->setMaxResults($max_results);

        return $query->getQuery()->getResult();

    }
}
