<?php

namespace AppBundle\Repository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    public function coursesIndex($max_results)
    {
        $query = $this->createQueryBuilder('c')
            ->leftJoin("c.category", "cat")
            ->leftJoin("c.provider", "p")
            ->setMaxResults($max_results);

        return $query->getQuery()->getResult();
    }

    public function findLastCourses($category, $max_results)
    {
        $query = $this->createQueryBuilder('c')
            ->leftJoin("c.provider", "pr")
            ->where("c.category = :id")
            ->orderBy("c.start", "DESC")
            ->setParameter('id', $category)
            ->setMaxResults($max_results);

        return $query->getQuery()->getResult();
    }


}
