<?php

namespace AppBundle\Repository;

/**
 * FavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findHearts($provider){
        $query = $this->createQueryBuilder('f')
            ->select("f")
            ->where("f.provider = :provider")
            ->setParameter("provider", $provider);

        return $query->getQuery()->getResult();
    }
}
