<?php

namespace AppBundle\Repository;

/**
 * OrdreBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdreBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
