<?php

namespace AppBundle\Repository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends \Doctrine\ORM\EntityRepository
{

    public function providersOfCategory($category)
    {
        $query = $this->createQueryBuilder('p')
            ->select("p as provider","avg(r.note) as note_avg", "count(r.note) as nmb_note")
            ->where('c = :category')
            ->leftJoin("p.categories", "c") /**IF INNERJOIN : result just with rating; LEFTJOIN : return ALL PROVIDERS*/
            ->leftJoin("p.ratings", "r")
            ->setParameter('category', $category)
            ->orderBy("note_avg",  "DESC")
            ->addOrderBy("nmb_note", "DESC")
            ->groupBy("p");

        return $query->getQuery()->getResult();
    }

    public function bestProviders($max_results)
    {
        $query = $this->createQueryBuilder('p')
            ->leftJoin("p.ratings", "r") /**IF INNERJOIN : result just with rating; LEFTJOIN : return ALL PROVIDERS*/
            ->select("p as provider","avg(r.note) as note_avg", "count(r.note) as nmb_note") /*round(avg(r.note), 2) - ne marche pas.  Fait en twig*/
            ->orderBy("note_avg",  "DESC")
            ->addOrderBy("nmb_note", "DESC")
            ->groupBy("p");

        if( is_integer($max_results)){
            $query->setMaxResults($max_results); /** LIMIT OF ROWS; IF NOT INTEGER  -  RETURN ALL PROVIDERS */
        }

        return $query->getQuery()->getResult();
    }

    public function findWithKeyword($keyword)
    {
        $qb = $this->createQueryBuilder('p');

        $qb ->select("p as provider","avg(r.note) as note_avg", "count(r.note) as nmb_note")
            ->where($qb->expr()->like('p.company', $qb->expr()->literal("%$keyword%")))
            ->leftJoin("p.ratings", "r")
            ->orderBy("note_avg", "DESC")
            ->addOrderBy("nmb_note", "DESC")
            ->groupBy("p");

        return $qb->getQuery()->getResult();
    }

    public function findWithLocality($locality)
    {
        $qb = $this->createQueryBuilder('p');

        $qb ->select("p as provider","avg(r.note) as note_avg", "count(r.note) as nmb_note")
            ->where('l = :locality')
            ->leftJoin("p.locality", "l")
            ->leftJoin("p.ratings", "r")
            ->setParameter('locality', $locality)
            ->orderBy("note_avg", "DESC")
            ->addOrderBy("nmb_note", "DESC")
            ->groupBy("p");

        return $qb->getQuery()->getResult();
    }

    public function findWithCategory($category)
    {
        $qb = $this->createQueryBuilder('p');

        $qb ->select("p as provider","avg(r.note) as note_avg", "count(r.note) as nmb_note")
            ->where('c = :category')
            ->leftJoin("p.categories", "c")
            ->leftJoin("p.ratings", "r")
            ->setParameter('category', $category)
            ->orderBy("note_avg", "DESC")
            ->addOrderBy("nmb_note", "DESC")
            ->groupBy("p");

        return $qb->getQuery()->getResult();
    }

    public function findWithLocalityCategory($locality,$category)
    {
        $qb = $this->createQueryBuilder('p')
            ->select("p as provider", "avg(r.note) as note_avg", "count(r.note) as nmb_note")
            ->leftJoin("p.ratings", "r")    ///LEFTJOIN retourne tous les items de la colonne de gauche peu importe les concordances
           /* ->leftJoin("p.locality", "l") /// INNERJOIN retourne tous les enregistrements comportant une concordance
            ->leftJoin("p.categories", "cs")
            ->addSelect('cs');

       // $qb = $qb->add('where', $qb->expr()->in(':c', 'cs'))*/
            ->where('p.locality = :locality')
            ->innerJoin('p.categories','c')
            ->andWhere('c = :category')
            ->addSelect("c")
            ->setParameter('category', $category)
            ->setParameter('locality', $locality)

            ->orderBy("note_avg", "DESC")
            ->addOrderBy("nmb_note", "DESC")
            ->groupBy("p");

            $query = $this->addJoins($qb);

        return $query->getQuery()->getResult();
    }
    /*
            $qb = $this->createQueryBuilder('p');
            $qb->Where('p.city = :city')
            ->setParameter('city', $city)
            ->join('p.serviceCategories', 'c', 'WITH', 'c = :category')
            ->addSelect('c')
            ->setParameter('category',$category);
            $query = $this->addJoins($qb);
            return $query->getQuery()->getResult();*/


    public function findWithKeywordLocality($keyword,$locality)
    {
        $qb = $this->createQueryBuilder('provider');

        $qb ->select("provider as p","avg(r.note) as note_avg", "count(r.note) as nmb_note")
            ->where($qb->expr()->like('provider.company', $qb->expr()->literal("%$keyword%")))
            ->andWhere('l = :locality')
            ->leftJoin("provider.locality", "l")
            ->leftJoin("provider.ratings", "r")
            ->setParameter('locality', $locality)
            ->orderBy("note_avg", "DESC")
            ->addOrderBy("nmb_note", "DESC")
            ->groupBy("p");

        return $qb->getQuery()->getResult();
    }

    public function findWithKeywordLocalityCategory($keyword,$locality,$category)
    {
        $qb = $this->createQueryBuilder('provider');

        $qb ->select("provider as p","avg(r.note) as note_avg", "count(r.note) as nmb_note")
            ->where($qb->expr()->like('provider.company', $qb->expr()->literal("%$keyword%")))
            ->andWhere('l = :locality')
            ->andWhere('c = :category')
            ->leftJoin("provider.locality", "l")
            ->leftJoin("provider.categories", "c")
            ->leftJoin("provider.ratings", "r")
            ->setParameter('locality', $locality)
            ->setParameter('category', $category)
            ->orderBy("note_avg", "DESC")
            ->addOrderBy("nmb_note", "DESC")
            ->groupBy("p");

        return $qb->getQuery()->getResult();
    }




}
