<?php

namespace AppBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRating($provider){
        $query = $this->createQueryBuilder('r')
            ->select("avg(r.note) as note_avg", "count(r.note) as nmb_note")
            ->where("r.provider = :provider")
            ->setParameter("provider", $provider);

        return $query->getQuery()->getResult();

    }
}
