<?php

namespace AppBundle\Repository;


/**
 * UsertempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsertempRepository extends \Doctrine\ORM\EntityRepository
{
    public function verifToken($token)
    {
        $query = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.token = :token')
            ->setParameter('token', $token);

        return $query->getQuery()->getResult();
    }
}
