security:
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
               class: AppBundle:User
               property: username


    role_hierarchy:
        ROLE_MEMBER:      ROLE_USER
        ROLE_PROVIDER:    ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_PROVIDER, ROLE_MEMBER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
                invalidate_session: false


    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
        AppBundle\Entity\User: bcrypt
        AppBundle\Entity\UserTemp: bcrypt

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/providers, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/promotions, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/courses, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/categories, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
