# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

# Ajout d'un encoder pour notre entité USer
    encoders:
        Symfony\Component\Security\Core\User\UserInterface:
            algorithm: sha512
        AppBundle\Entity\User:
            algorithm: sha512
            cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    ##member:  { password: memberpass, roles: [ 'ROLE_MEMBER' ] }
                    #provider:  { password: providerpass, roles: [ 'ROLE_PROVIDER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }



    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        main_login:
            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu

        main:
            pattern: ^/
            anonymous: true
            #entity: { class: AppBundle\Entity\User, property: username }

            provider:  in_memory #main

            form_login:
                login_path: login
                check_path: login_check

            logout:
                path: /logout
                target: /platform

           # remember_me:
            #   key: "%secret%"
              #  lifetime: 2232000


    role_hierarchy:
        ROLE_ADMIN:       [ROLE_MEMBER, ROLE_PROVIDER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }